baseURL = 'https://yoshitomo-matsubara.net'
languageCode = 'en-us'
title = "Yoshitomo Matsubara's Personal Webpage"
theme = "personal_theme"
relativeURLS = true
enableRobotsTXT = true
# googleAnalytics = "G-5ZP208NTBV"


[params]
  author = "Yoshitomo Matsubara"
  description = "Yoshitomo Matsubara's personal webpage"


[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.8


[permalinks]
  blog = '/blog/:year/:month/:day/:title/'


[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"

  [[module.mounts]]
    source = "node_modules/bootstrap-icons/font/bootstrap-icons.scss"
    target = "assets/scss/bootstrap-icons.scss"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "node_modules/bootstrap-icons/font/fonts"
    target = "static/css/fonts"


[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]


sectionPagesMenu = "main"


[menu]
  [[menu.main]]
    identifier = "projects"
    title = "Projects"
    url = "/projects/"
    weight = 200
    name = "bi bi-lightbulb"

#  [[menu.main]]
#    identifier = "blog"
#    title = "Blog"
#    url = "/blog/"
#    weight = 400
#    name = "bi bi-chat-square-dots"
